### ISSUE TITLE
Adding and removing items is slow

### ISSUE THREAD

**Issue by AlexanderFabisch** [envire/envire-envire_visualizer#5]
Our current strategy to update items in the visualizer is to remove old items and add a new one. This approach has drawbacks:
* it is slow: if I don't wait for 0.2 s after updating an item, it the visualizer will crash or freeze
* the display properties on the right side of the visualizer a continuously removed and readded, their order changes and the configuration is reset

I just want to document these problems with this ticket here. No immediate action is required. @Rauldg will probably talk to @arneboe about these issues.

**Comment by arneboe** [comment]
> it is slow: if I don't wait for 0.2 s after updating an item, it the visualizer will crash or freeze

It shouldn't crash and freeze. I am doing the same thing in a test case without any delay and it works. Can you provide a backtrace?

> the display properties on the right side of the visualizer a continuously removed and readded, their order changes and the configuration is reset

This is a problem with loading/unloading vizkit plugins. It's nothing I can change.

In the log run there should be an api for modifying items. However this is a hard problem and I currently dont see a good solution.

**Comment by AlexanderFabisch** [comment]
mmh... no, I cannot provide a backtrace, it usually works now.

However, if I don't wait before I start my worker thread (where the graph is redrawn), the visualizer consistently freezes. If I increase this time, it does not happen as often but it sometimes happens.

**Comment by Rauldg** [comment]
@planthaber is also using the envire visulizer. Did you came accross this issue too?

**Comment by planthaber** [comment]
I already talked to arne.

I prepared a pull request, that hopefully will lead to better performance: https://github.com/envire/envire-envire_core/pull/27

If that one is merged, we can notify changes without removing and re-adding item to the graph, that will also give us the opportunity not to reload the visualization plugins on changes.

**Comment by AlexanderFabisch** [comment]
Yeah. That's awesome. :)
